import 'dotenv/config';

export const {
    PORT,
    MONGO_URI,
    WEB_GOOGLE_CLIENT_ID,
    ANDROID_GOOGLE_GOOGLE_CLIENT_ID,
    IOS_GOOGLE_GOOGLE_CLIENT_ID,
    ACCESS_TOKEN_SECRET,
    ACCESS_TOKEN_EXPIRY,
    REFRESH_TOKEN_SECRET,
    REFRESH_TOKEN_EXPIRY,
    COOKIE_PASSWORD,
    SEED_SECRET,
    ADMIN_LOGIN_EMAIL,
    ADMIN_LOGIN_PASSWORD,
} = process.env;
