import {ISeat} from "./models/BusSchema";

export const locations = [
    'Lucknow',
    'Delhi',
    'Mumbai',
    'Bangalore',
    'Chennai',
    'Kolkata',
    'Hyderabad',
    'Pune',
    'Jaipur',
    'Ahmedabad',
    'Indore',
    'Surat',
    'Nagpur',
    'Patna',
    'Bhopal',
    'Chandigarh',
    'Goa',
    'Visakhapatnam',
    'Guwahati',
    'Ranchi',
];

export const buses = [
    {
        busId: 'bus_001',
        company: 'Sethi Yatra',
        busType: 'A/C Seater',
        price: 899,
        originalPrice: 999,
        rating: 4.5,
        totalReviews: 720,
        badges: ['Comfortable Ride', 'Well Maintained'],
    },
    {
        busId: 'bus_002',
        company: 'RedBus Travels',
        busType: 'A/C Sleeper',
        price: 999,
        originalPrice: 1099,
        rating: 4.7,
        totalReviews: 950,
        badges: ['Highly Rated', 'New Bus'],
    },
    {
        busId: 'bus_003',
        company: 'GoBus',
        busType: 'Non-A/C Seater',
        price: 699,
        originalPrice: 799,
        rating: 4.2,
        totalReviews: 530,
        badges: ['Affordable', 'Great Service'],
    },
    {
        busId: 'bus_004',
        company: 'National Express',
        busType: 'A/C Sleeper',
        price: 1199,
        originalPrice: 1299,
        rating: 4.8,
        totalReviews: 1100,
        badges: ['Premium Experience', 'Fast Service'],
    },
    {
        busId: 'bus_005',
        company: 'GreenLine Travels',
        busType: 'Non-A/C Sleeper',
        price: 799,
        originalPrice: 899,
        rating: 4.1,
        totalReviews: 400,
        badges: ['Budget Friendly', 'Good Seats'],
    },
    {
        busId: 'bus_006',
        company: 'InterCity',
        busType: 'A/C Seater',
        price: 950,
        originalPrice: 1050,
        rating: 4.3,
        totalReviews: 610,
        badges: ['Comfortable Ride', 'WiFi Available'],
    },
    {
        busId: 'bus_007',
        company: 'Travellers Hub',
        busType: 'A/C Sleeper',
        price: 1100,
        originalPrice: 1200,
        rating: 4.6,
        totalReviews: 880,
        badges: ['Well Maintained', 'Snack Included'],
    },
    {
        busId: 'bus_008',
        company: 'Metro Travels',
        busType: 'Non-A/C Seater',
        price: 650,
        originalPrice: 750,
        rating: 3.9,
        totalReviews: 320,
        badges: ['Affordable', 'Spacious Seats'],
    },
    {
        busId: 'bus_009',
        company: 'ExpressLine',
        busType: 'A/C Sleeper',
        price: 1250,
        originalPrice: 1350,
        rating: 4.9,
        totalReviews: 1300,
        badges: ['Luxury Coach', 'Fast Service'],
    },
    {
        busId: 'bus_010',
        company: 'Sunrise Travels',
        busType: 'Non-A/C Sleeper',
        price: 820,
        originalPrice: 920,
        rating: 4.0,
        totalReviews: 450,
        badges: ['Budget Friendly', 'Night Service'],
    },
    /*{
        busId: 'bus_011',
        company: 'UltraBus',
        busType: 'A/C Seater',
        price: 980,
        originalPrice: 1080,
        rating: 4.4,
        totalReviews: 700,
        badges: ['WiFi Available', 'On-time'],
    },
    {
        busId: 'bus_012',
        company: 'Skyline Express',
        busType: 'A/C Sleeper',
        price: 1150,
        originalPrice: 1250,
        rating: 4.7,
        totalReviews: 900,
        badges: ['Premium Experience', 'Well Maintained'],
    },
    {
        busId: 'bus_013',
        company: 'Royal Coach',
        busType: 'Non-A/C Seater',
        price: 720,
        originalPrice: 820,
        rating: 4.1,
        totalReviews: 480,
        badges: ['Great Service', 'Spacious Seats'],
    },
    {
        busId: 'bus_014',
        company: 'JourneyCo',
        busType: 'A/C Seater',
        price: 930,
        originalPrice: 1030,
        rating: 4.2,
        totalReviews: 650,
        badges: ['Comfortable Ride', 'Snack Included'],
    },
    {
        busId: 'bus_015',
        company: 'Swift Riders',
        busType: 'Non-A/C Sleeper',
        price: 810,
        originalPrice: 910,
        rating: 4.0,
        totalReviews: 420,
        badges: ['Night Service', 'Budget Friendly'],
    },
    {
        busId: 'bus_016',
        company: 'Vista Travels',
        busType: 'A/C Sleeper',
        price: 1200,
        originalPrice: 1300,
        rating: 4.8,
        totalReviews: 1020,
        badges: ['Luxury Coach', 'Fast Service'],
    },
    {
        busId: 'bus_017',
        company: 'Allied Transport',
        busType: 'A/C Seater',
        price: 970,
        originalPrice: 1070,
        rating: 4.3,
        totalReviews: 680,
        badges: ['On-time', 'WiFi Available'],
    },
    {
        busId: 'bus_018',
        company: 'CityLink',
        busType: 'Non-A/C Seater',
        price: 680,
        originalPrice: 780,
        rating: 3.8,
        totalReviews: 300,
        badges: ['Affordable', 'Good Seats'],
    },
    {
        busId: 'bus_019',
        company: 'Premium Wheels',
        busType: 'A/C Sleeper',
        price: 1180,
        originalPrice: 1280,
        rating: 4.6,
        totalReviews: 890,
        badges: ['Well Maintained', 'Comfortable Ride'],
    },
    {
        busId: 'bus_020',
        company: 'RoadStar',
        busType: 'Non-A/C Sleeper',
        price: 830,
        originalPrice: 930,
        rating: 4.1,
        totalReviews: 460,
        badges: ['Night Service', 'Spacious Seats'],
    },
    {
        busId: 'bus_021',
        company: 'Elite Coaches',
        busType: 'A/C Seater',
        price: 990,
        originalPrice: 1090,
        rating: 4.5,
        totalReviews: 750,
        badges: ['On-time', 'Snack Included'],
    },
    {
        busId: 'bus_022',
        company: 'Comfort Travels',
        busType: 'A/C Sleeper',
        price: 1220,
        originalPrice: 1320,
        rating: 4.7,
        totalReviews: 950,
        badges: ['Premium Experience', 'WiFi Available'],
    },
    {
        busId: 'bus_023',
        company: 'Holiday Express',
        busType: 'Non-A/C Seater',
        price: 710,
        originalPrice: 810,
        rating: 4.0,
        totalReviews: 430,
        badges: ['Budget Friendly', 'Good Service'],
    },
    {
        busId: 'bus_024',
        company: 'SuperFast',
        busType: 'A/C Seater',
        price: 960,
        originalPrice: 1060,
        rating: 4.4,
        totalReviews: 720,
        badges: ['Fast Service', 'On-time'],
    },
    {
        busId: 'bus_025',
        company: 'EconoBus',
        busType: 'Non-A/C Sleeper',
        price: 780,
        originalPrice: 880,
        rating: 3.9,
        totalReviews: 390,
        badges: ['Affordable', 'Night Service'],
    },*/
];

export const generateSeats = (): ISeat[][] => {
    const seats: ISeat[] = [];

    for (let i = 1; i <= 28; i++) {
        let seatType: ISeat['seatType'];

        if (i > 24) {
            seatType = i % 4 === 1 ? 'window' : 'side';
        } else {
            seatType = i % 4 === 1 ? 'window' : i % 4 === 2 ? 'path' : 'side';
        }

        seats.push({
            seatId: i,
            seatType,
            isBooked: false,
        });
    }

    return Array.from({length: 7}, (_, row) => seats.slice(row * 4, row * 4 + 4));
}
